name: "randomized_smoothing_eurosat_dinov2_large"
use_embeddings: False
wandb_project: "randomized-smoothing-eurosat"
dataset:
  dir: "/data/datasets/EuroSAT_RGB"
  name: 'eurosat_classification'
  # dir: "/data/datasets/GTSRB/GTSRB"
  # name: 'gtsrb_classification'
  tag: ['image','dinov2_large','classification']
model:
  input_modality: "image"
  randomized_smoothing:
    name: "randomized_smoothing"
    noise_std: 1.0
  backbone:
    name: "dinov2_large"
    width: 224
    height: 224
  head:
    name: "classification_head"
    input_dim: 1024
    hidden_dims: [512]
    output_dim: 10
    dropout: 0.5
optimizer:
  epochs: 30
  warmup: 5
  lr: 0.0001
  weight_decay: 0.02
  # lr: 0.0005