name: "sunrgb_imagebind_huge"
use_embeddings: True
wandb_project: "robust-retrieval-augmentation-sunrgb"
dataset:
  dir: '/data/datasets/SUNRGBD'
  name: 'sunrgbd_classification'
  tag: ['image','imagebind_huge','classification']
model:
  input_modality: "image"
  backbone:
    name: "imagebind_huge"
    width: 224
    height: 224
    modality: 'image'
  retrieval_augmentation:
    name: "robust_augmentation"
    key: "image"
    key_tag: ['image', 'imagebind_huge', 'classification']
    value: "image"
    value_tag: ['image', 'imagebind_huge', 'classification']
    alpha: 1.0
    temperature: 0.0001
  head:
    name: "classification_head"
    input_dim: 1024
    hidden_dims: [512]
    output_dim: 19
    dropout: 0.5
optimizer:
  epochs: 40
  warmup: 5
  lr: 0.0002
  weight_decay: 0.03
    